### ISSUE TITLE
Forge issues

### ISSUE THREAD

**Issue by Taj500** [AOF-Dev/MCinaBox#1006]
I installed forge for 1.16.5, when I tried to launch the game and it just stays on a white screen. Nothing happens at all. 

 - Device: Google pixel 5
 - OS: Android - 11
 - App Version: v0.1.4 - p5
 - CPU architecture:  arm64 

Now I did try running forge for 1.12.2, and it worked until I added mods. It had the same issue as my other forge installation. Just a white screen. I also of course ran both of these versions vanilla before I tried forge.

**Comment by artdeell** [comment]
wow googol pixel 5

also afaik mcinabox has issues wint 1.13+ in newer versions

**Comment by Taj500** [comment]
> wow googol pixel 5
> 
> also afaik mcinabox has issues wint 1.13+ in newer versions

Hmm weird. What would explain the 1.12.2 issues?

**Comment by artdeell** [comment]
A log file

**Comment by Taj500** [comment]
> A log file

Maybe this helps?



18:52:19] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:644]:     at java.lang.ClassLoader.defineClass1(Native Method)
[18:52:19] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:644]:     at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
[18:52:19] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:644]:     at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[18:52:19] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:644]:     at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
[18:52:19] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:644]:     ... 6 more
[18:52:19] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:668]: Caused by: java.lang.ClassNotFoundException: net.ilexiconn.llibrary.server.asm.RuntimePatcher
[18:52:19] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:668]:     at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
[18:52:19] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:668]:     at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
[18:52:19] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:668]:     at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
[18:52:19] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:668]:     ... 10 more
