### ISSUE TITLE
I cant sign into online accounts

### ISSUE THREAD

**Issue by NightmareYT46** [AOF-Dev/MCinaBox#1053]
**Describe the bug**

**To Reproduce**
1. Go to accounts
2. Click on create new
3. Scroll down to login

I expaected to put in my info and get logged in

**Screenshots**

 - Device: [e.g. Samsung Galaxy A20
 - OS: [e.g. Android 10
 - App Version [e.g. v0.1.3]
 - CPU architecture [e.g. arm64]  

**Additional context**

**Comment by SergueiKhadirov** [comment]
you try to log in with mojang account of microsoft account ?

**Comment by DreamOneTop** [comment]
McInabox can't log in with Microsoft account.
I think you can try to log in with a Mojang account.
You can also try to use PojavLauncher.

**Comment by grimrea3645B** [comment]
Same thing happens to me I can't sign into my Microsoft account
Here is what it gives me


java.lang.RuntimeException: 

MSA Error: 401: Unauthorized, error stream:
{"Identity":"0","XErr":2148916238,"Message":"","Redirect":"https://start.ui.xboxlive.com/AddChildToFamily"}
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.throwResponseError(Msa.java:292)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXsts(Msa.java:169)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXBLToken(Msa.java:122)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireAccessToken(Msa.java:75)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.<init>(Msa.java:35)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:72)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:22)
	at android.os.AsyncTask$3.call(AsyncTask.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
 I'm using the redmi 9i 
Android 10

App version the newest one

Runtime aarch 64
