### ISSUE TITLE
Ticking entity crash

### ISSUE THREAD

**Issue by Kotarou2k4** [AOF-Dev/MCinaBox#208]
This issue happening on 1.12.2 and maybe from 1.9 and above. I'm playing normally then it crashed
Sorry for my bad english
---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 6/13/20 2:49 AM
Description: Ticking entity

java.lang.IndexOutOfBoundsException: Index: 7, Size: 7
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.remove(ArrayList.java:496)
	at net.minecraft.util.math.BlockPos$PooledMutableBlockPos.func_185339_c(SourceFile:455)
	at net.minecraft.util.math.BlockPos$PooledMutableBlockPos.func_185345_c(SourceFile:445)
	at net.minecraft.entity.EntityLivingBase.func_191986_a(EntityLivingBase.java:1909)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2393)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:678)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178)
	at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:43)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.remove(ArrayList.java:496)
	at net.minecraft.util.math.BlockPos$PooledMutableBlockPos.func_185339_c(SourceFile:455)
	at net.minecraft.util.math.BlockPos$PooledMutableBlockPos.func_185345_c(SourceFile:445)
	at net.minecraft.entity.EntityLivingBase.func_191986_a(EntityLivingBase.java:1909)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2393)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:678)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178)
	at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:43)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)

-- Entity being ticked --
Details:
	Entity Type: minecraft:cow (net.minecraft.entity.passive.EntityCow)
	Entity ID: 73
	Entity Name: Cow
	Entity's Exact location: 253.17, 64.00, 266.48
	Entity's Block location: World: (253,64,266), Chunk: (at 13,4,10 in 15,16; contains blocks 240,0,256 to 255,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: eee
	All players: 1 total; [EntityPlayerMP['dkdkd'/632, l='eee', x=266.87, y=64.00, z=264.79]]
	Chunk stats: ServerChunkCache: 256 Drop: 0
	Level seed: -8672190896246383448
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (256,64,256), Chunk: (at 0,4,0 in 16,16; contains blocks 256,0,256 to 271,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 972 game time, 972 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 100775 (now: false), thunder time: 72324 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (arm) version 4.4.153-perf+
	Java Version: 1.8.0-internal, Oracle Corporation
	Java VM Version: OpenJDK Client VM (mixed mode), Oracle Corporation
	Memory: 202673376 bytes (193 MB) / 514990080 bytes (491 MB) up to 746061824 bytes (711 MB)
	JVM Flags: 2 total; -Xmx735m -Xms128m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_F5 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID        | Version      | Source                        | Signature |
	|:------ |:--------- |:------------ |:----------------------------- |:--------- |
	| LCHIJA | minecraft | 1.12.2       | minecraft.jar                 | None      |
	| LCHIJA | mcp       | 9.42         | minecraft.jar                 | None      |
	| LCHIJA | FML       | 8.0.99.99    | forge-1.12.2-14.23.5.2847.jar | None      |
	| LCHIJA | forge     | 14.23.5.2847 | forge-1.12.2-14.23.5.2847.jar | None      |

	Loaded coremods (and transformers): 
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['dkdkd'/632, l='eee', x=266.87, y=64.00, z=264.79]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 4
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.0 gl4es wrapper 1.1.2
	OpenGlRenderer: GL4ES wrapper
	OpenGlVendor: ptitSeb
	CpuCount: 7

**Comment by artdeell** [comment]
It's because Minecraft attempts to make a screenshot for world icon, but it resukts in ticking entity crash. Because GL4ES OpenGL is far from ideal.

**Comment by Kotarou2k4** [comment]
What do you mean "GL4ES OpenGL is far from ideal" ? Sorry, i'm not good at programing

**Comment by artdeell** [comment]
i mean that it's still sort of emulation, not 100% as original, which leads to errors.

**Comment by CosineMath** [comment]
Sorry to tell you we don't know what caused this error. 
(It seems not to be the fault of MCinaBox. If you google this error, you might find that many other people met this error before. But we do NOT know the real reason now.)

It's reported that changing the configuration of Forge helps:
find the `.minecraft/config/forge.cfg` in your phone and open the file `forge.cfg`
forge.cfg:
`...
B:removeErroringEntities=false
B:removeErroringTileEntities=false
...`

change to 
`...
B:removeErroringEntities=true
B:removeErroringTileEntities=true
...`

**Comment by Kotarou2k4** [comment]
But I think it's have a very simple reason. Because my phone (Redmi Note 7 Snap660) is not powerful enough so ticking too many entity cause crash :v
