### ISSUE TITLE
Mcinabox 1.4 crashing when launching app

### ISSUE THREAD

**Issue by blissband123** [AOF-Dev/MCinaBox#447]
i cant run 1.3 version fine but when i update to 1.4 it wont even load the app

**Comment by friendlyfredward** [comment]
What device are you using, and what version of Android is it on? This info could be helpful to the developers so they can fix it. Also if you can find any crash or error log that might say what caused the app to stop

**Comment by blissband123** [comment]
Mine is a galaxy s8 thats on andriod pie 
And ill just copy the crash notes:

---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 10/1/20 6:36 AM
Description: Unexpected error

java.lang.ArrayIndexOutOfBoundsException
	at java.lang.System.arraycopy(Native Method)
	at java.nio.HeapByteBuffer.put(HeapByteBuffer.java:207)
	at org.lwjgl.opengl.EventQueue.putEvent(EventQueue.java:78)
	at org.lwjgl.opengl.BoatKeyboard.putKeyboardEvent(BoatKeyboard.java:202)
	at org.lwjgl.opengl.BoatKeyboard.flushDeferredEvent(BoatKeyboard.java:381)
	at org.lwjgl.opengl.BoatKeyboard.poll(BoatKeyboard.java:192)
	at org.lwjgl.opengl.BoatDisplay.pollKeyboard(BoatDisplay.java:1444)
	at org.lwjgl.input.Keyboard.poll(Keyboard.java:387)
	at org.lwjgl.opengl.Display.pollDevices(Display.java:680)
	at org.lwjgl.opengl.Display.processMessages(Display.java:604)
	at org.lwjgl.opengl.Display.update(Display.java:668)
	at org.lwjgl.opengl.Display.update(Display.java:630)
	at bao.g(SourceFile:869)
	at bao.ak(SourceFile:838)
	at bao.f(SourceFile:728)
	at net.minecraft.client.main.Main.main(SourceFile:148)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.lang.System.arraycopy(Native Method)
	at java.nio.HeapByteBuffer.put(HeapByteBuffer.java:207)
	at org.lwjgl.opengl.EventQueue.putEvent(EventQueue.java:78)
	at org.lwjgl.opengl.BoatKeyboard.putKeyboardEvent(BoatKeyboard.java:202)
	at org.lwjgl.opengl.BoatKeyboard.flushDeferredEvent(BoatKeyboard.java:381)
	at org.lwjgl.opengl.BoatKeyboard.poll(BoatKeyboard.java:192)
	at org.lwjgl.opengl.BoatDisplay.pollKeyboard(BoatDisplay.java:1444)
	at org.lwjgl.input.Keyboard.poll(Keyboard.java:387)
	at org.lwjgl.opengl.Display.pollDevices(Display.java:680)
	at org.lwjgl.opengl.Display.processMessages(Display.java:604)
	at org.lwjgl.opengl.Display.update(Display.java:668)
	at org.lwjgl.opengl.Display.update(Display.java:630)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [bjk['jeff'/436, l='MpServer', x=-216.81, y=65.62, z=232.72]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-232,64,252), Chunk: (at 8,4,12 in -15,15; contains blocks -240,0,240 to -225,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 481 game time, 481 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 118 total; [yq['Zombie'/2078, l='MpServer', x=-140.50, y=63.00, z=157.50], yl['Skeleton'/2108, l='MpServer', x=-144.50, y=46.00, z=200.50], yl['Skeleton'/2109, l='MpServer', x=-146.50, y=46.00, z=199.50], yl['Skeleton'/2110, l='MpServer', x=-145.50, y=46.00, z=199.50], wv['Wolf'/91, l='MpServer', x=-296.50, y=70.00, z=266.50], wv['Wolf'/92, l='MpServer', x=-296.50, y=67.00, z=264.50], wv['Wolf'/93, l='MpServer', x=-296.50, y=70.00, z=266.50], wv['Wolf'/94, l='MpServer', x=-296.50, y=72.00, z=269.50], wi['Donkey'/111, l='MpServer', x=-260.50, y=70.00, z=164.78], wi['Donkey'/112, l='MpServer', x=-256.50, y=70.00, z=166.50], wo['Pig'/113, l='MpServer', x=-260.50, y=70.00, z=166.53], wo['Pig'/114, l='MpServer', x=-258.50, y=70.00, z=167.50], wo['Pig'/115, l='MpServer', x=-260.50, y=71.00, z=168.09], wo['Pig'/116, l='MpServer', x=-262.50, y=70.00, z=167.50], wi['Horse'/117, l='MpServer', x=-262.50, y=69.00, z=211.50], wi['Horse'/118, l='MpServer', x=-259.50, y=69.00, z=210.50], wi['Horse'/119, l='MpServer', x=-261.87, y=69.00, z=208.13], wi['Donkey'/120, l='MpServer', x=-252.91, y=69.00, z=220.50], wi['Donkey'/121, l='MpServer', x=-255.22, y=69.00, z=220.50], wi['Donkey'/122, l='MpServer', x=-252.75, y=69.00, z=218.63], wi['Donkey'/123, l='MpServer', x=-254.78, y=69.00, z=216.53], wi['Donkey'/124, l='MpServer', x=-253.00, y=69.00, z=214.13], wi['Donkey'/125, l='MpServer', x=-250.84, y=69.00, z=215.88], xz['Creeper'/5253, l='MpServer', x=-262.75, y=42.00, z=275.94], xz['Creeper'/5254, l='MpServer', x=-262.97, y=42.00, z=275.00], xz['Creeper'/5255, l='MpServer', x=-269.47, y=41.17, z=276.70], wi['Horse'/136, l='MpServer', x=-244.59, y=69.00, z=211.97], wi['Horse'/137, l='MpServer', x=-246.50, y=68.00, z=218.72], yl['Skeleton'/5257, l='MpServer', x=-261.10, y=42.00, z=279.69], wi['Horse'/138, l='MpServer', x=-253.19, y=69.00, z=208.94], wi['Horse'/139, l='MpServer', x=-242.19, y=69.00, z=215.31], wi['Horse'/140, l='MpServer', x=-243.84, y=68.00, z=219.00], wi['Horse'/141, l='MpServer', x=-251.72, y=69.00, z=212.97], xz['Creeper'/2189, l='MpServer', x=-241.31, y=18.00, z=292.50], wv['Wolf'/142, l='MpServer', x=-238.56, y=69.00, z=260.59], wv['Wolf'/143, l='MpServer', x=-247.75, y=72.00, z=257.50], wv['Wolf'/144, l='MpServer', x=-245.09, y=68.00, z=261.47], wv['Wolf'/145, l='MpServer', x=-233.59, y=68.95, z=262.38], wi['Horse'/146, l='MpServer', x=-240.50, y=70.00, z=300.50], wi['Horse'/147, l='MpServer', x=-243.50, y=71.00, z=296.50], wi['Horse'/148, l='MpServer', x=-238.87, y=70.00, z=299.13], wi['Horse'/155, l='MpServer', x=-216.50, y=63.00, z=186.50], wv['Wolf'/156, l='MpServer', x=-212.72, y=68.00, z=252.78], wv['Wolf'/157, l='MpServer', x=-232.55, y=67.69, z=262.51], wv['Wolf'/158, l='MpServer', x=-214.83, y=68.00, z=263.50], wv['Wolf'/159, l='MpServer', x=-221.09, y=64.00, z=257.25], wv['Wolf'/175, l='MpServer', x=-187.75, y=71.00, z=268.97], wv['Wolf'/176, l='MpServer', x=-193.44, y=65.00, z=268.50], wv['Wolf'/177, l='MpServer', x=-192.19, y=65.00, z=268.69], wv['Wolf'/178, l='MpServer', x=-188.50, y=67.00, z=270.50], wv['Wolf'/179, l='MpServer', x=-182.50, y=72.00, z=169.50], yl['Skeleton'/5299, l='MpServer', x=-239.50, y=29.00, z=304.50], wv['Wolf'/180, l='MpServer', x=-179.50, y=75.00, z=172.50], yl['Skeleton'/5300, l='MpServer', x=-242.50, y=29.00, z=304.50], wv['Wolf'/181, l='MpServer', x=-180.50, y=75.00, z=173.50], yl['Skeleton'/5301, l='MpServer', x=-244.50, y=29.00, z=304.50], wv['Wolf'/182, l='MpServer', x=-181.50, y=75.00, z=176.50], yq['Zombie'/5302, l='MpServer', x=-240.50, y=29.00, z=308.50], wi['Horse'/185, l='MpServer', x=-172.87, y=67.00, z=313.13], wi['Horse'/186, l='MpServer', x=-170.50, y=67.00, z=314.50], wi['Horse'/192, l='MpServer', x=-152.50, y=66.00, z=220.50], wi['Horse'/198, l='MpServer', x=-146.69, y=67.00, z=253.06], xz['Creeper'/2246, l='MpServer', x=-162.09, y=38.00, z=173.25], wi['Horse'/200, l='MpServer', x=-148.50, y=67.00, z=257.50], wi['Horse'/201, l='MpServer', x=-141.06, y=66.00, z=250.06], we['Bat'/5368, l='MpServer', x=-185.63, y=14.77, z=308.92], we['Bat'/1314, l='MpServer', x=-202.63, y=26.15, z=310.61], we['Bat'/5414, l='MpServer', x=-153.25, y=40.00, z=161.25], ya['Enderman'/2370, l='MpServer', x=-146.47, y=39.00, z=164.47], ya['Enderman'/2371, l='MpServer', x=-145.69, y=40.00, z=168.03], ya['Enderman'/2372, l='MpServer', x=-144.50, y=40.00, z=170.50], xz['Creeper'/1403, l='MpServer', x=-209.84, y=28.00, z=293.22], yq['Zombie'/1404, l='MpServer', x=-211.50, y=28.00, z=293.50], yq['Zombie'/2454, l='MpServer', x=-144.50, y=36.00, z=238.50], yl['Skeleton'/1454, l='MpServer', x=-183.50, y=27.00, z=193.50], ws['Squid'/458, l='MpServer', x=-181.31, y=58.31, z=232.75], ws['Squid'/459, l='MpServer', x=-188.53, y=60.00, z=231.47], ws['Squid'/460, l='MpServer', x=-181.16, y=60.06, z=240.34], ws['Squid'/461, l='MpServer', x=-184.34, y=59.41, z=236.95], bjk['jeff'/436, l='MpServer', x=-216.81, y=65.62, z=232.72], xk['item.item.seeds'/2611, l='MpServer', x=-233.69, y=67.13, z=267.53], xz['Creeper'/2639, l='MpServer', x=-173.50, y=21.00, z=165.50], xz['Creeper'/2640, l='MpServer', x=-173.50, y=21.00, z=161.50], yq['Zombie'/1638, l='MpServer', x=-182.69, y=14.00, z=188.59], we['Bat'/643, l='MpServer', x=-159.17, y=27.23, z=170.35], yq['Zombie'/662, l='MpServer', x=-269.50, y=24.00, z=294.50], yq['Zombie'/663, l='MpServer', x=-269.50, y=24.00, z=295.50], yq['Zombie'/1700, l='MpServer', x=-157.50, y=40.00, z=168.50], yl['Skeleton'/1701, l='MpServer', x=-269.50, y=48.00, z=252.50], yl['Skeleton'/1702, l='MpServer', x=-269.50, y=48.00, z=250.50], we['Bat'/679, l='MpServer', x=-154.11, y=33.00, z=239.41], we['Bat'/680, l='MpServer', x=-155.48, y=34.77, z=235.05], yq['Zombie'/1730, l='MpServer', x=-253.50, y=43.00, z=274.50], yq['Zombie'/1753, l='MpServer', x=-240.50, y=29.00, z=309.50], yq['Zombie'/1754, l='MpServer', x=-242.50, y=29.00, z=301.50], xz['Creeper'/1755, l='MpServer', x=-245.97, y=30.00, z=301.66], yl['Skeleton'/1756, l='MpServer', x=-239.50, y=29.00, z=309.50], xz['Creeper'/757, l='MpServer', x=-142.28, y=34.00, z=244.44], xz['Creeper'/2830, l='MpServer', x=-174.50, y=21.00, z=161.50], xz['Creeper'/2831, l='MpServer', x=-172.50, y=21.00, z=159.50], xz['Creeper'/2832, l='MpServer', x=-172.50, y=21.00, z=160.50], xz['Creeper'/2833, l='MpServer', x=-170.50, y=21.00, z=163.50], yl['Skeleton'/2838, l='MpServer', x=-261.50, y=41.00, z=270.50], yl['Skeleton'/2839, l='MpServer', x=-261.50, y=41.00, z=271.50], yl['Skeleton'/2840, l='MpServer', x=-260.50, y=41.00, z=272.50], yq['Zombie'/2841, l='MpServer', x=-145.50, y=36.00, z=237.50], yq['Zombie'/2842, l='MpServer', x=-144.50, y=36.00, z=237.50], xz['Creeper'/2855, l='MpServer', x=-160.50, y=38.00, z=166.50], xz['Creeper'/2856, l='MpServer', x=-160.50, y=38.00, z=169.50], xz['Creeper'/2857, l='MpServer', x=-165.50, y=38.00, z=170.50], yq['Zombie'/2858, l='MpServer', x=-164.50, y=38.00, z=169.50], ya['Enderman'/1844, l='MpServer', x=-271.50, y=24.00, z=293.50], xk['item.item.seeds'/2884, l='MpServer', x=-230.75, y=67.13, z=271.59], yl['Skeleton'/1920, l='MpServer', x=-229.50, y=16.00, z=284.50], yl['Skeleton'/1921, l='MpServer', x=-228.50, y=16.00, z=284.50], yl['Skeleton'/1939, l='MpServer', x=-262.50, y=42.00, z=289.50], yl['Skeleton'/1940, l='MpServer', x=-261.50, y=42.00, z=287.50], xz['Creeper'/2015, l='MpServer', x=-275.50, y=30.00, z=312.50]]
	Retry entities: 0 total; []
	Server brand: vanilla
	Server type: Integrated singleplayer server
Stacktrace:
	at bjf.a(SourceFile:289)
	at bao.b(SourceFile:1972)
	at bao.f(SourceFile:742)
	at net.minecraft.client.main.Main.main(SourceFile:148)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Linux (arm) version 4.4.153-17214672
	Java Version: 1.8.0-internal, Oracle Corporation
	Java VM Version: OpenJDK Client VM (mixed mode), Oracle Corporation
	Memory: 99208336 bytes (94 MB) / 243163136 bytes (231 MB) up to 259522560 bytes (247 MB)
	JVM Flags: 2 total; -Xmx256m -Xms128m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	Launched Version: MCinaBox_0.1.4-p3
	LWJGL: 2.9.3
	OpenGL: GL4ES wrapper GL version 2.0 gl4es wrapper 1.1.2, ptitSeb
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because ARB_shader_objects, ARB_vertex_shader, and ARB_fragment_shader are supported.

	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by OffRiSe72** [comment]
i have the same problem with the same phone.

**Comment by OffRiSe72** [comment]
on my phone the app doesnt even launch
