### ISSUE TITLE
How to fix this 

### ISSUE THREAD

**Issue by KUALALUM** [AOF-Dev/MCinaBox#499]
I try mod replay cinematic when i record it. It crash and my replay were not save 😩😩😩.

Here the crash report
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 10/9/20 12:27 PM
Description: Saving replay file

java.nio.file.NoSuchFileException: /tmp/replaystudio4918167575117501656replayfile
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.createFile(Files.java:632)
	at java.nio.file.TempFileHelper.create(TempFileHelper.java:138)
	at java.nio.file.TempFileHelper.createTempFile(TempFileHelper.java:161)
	at java.nio.file.Files.createTempFile(Files.java:897)
	at com.replaymod.replaystudio.replay.ZipReplayFile.save(ZipReplayFile.java:323)
	at com.replaymod.recording.packet.PacketListener.lambda$channelInactive$9(PacketListener.java:266)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (arm) version 3.18.24-perf-gecf4690a7
	Java Version: 1.8.0-internal, Oracle Corporation
	Java VM Version: OpenJDK Client VM (mixed mode), Oracle Corporation
	Memory: 328255576 bytes (313 MB) / 597745664 bytes (570 MB) up to 918355968 bytes (875 MB)
	JVM Flags: 2 total; -Xmx906m -Xms128m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID        | Version      | Source                        | Signature |
	|:------ |:--------- |:------------ |:----------------------------- |:--------- |
	| LCHIJA | minecraft | 1.12.2       | minecraft.jar                 | None      |
	| LCHIJA | mcp       | 9.42         | minecraft.jar                 | None      |
	| LCHIJA | FML       | 8.0.99.99    | forge-1.12.2-14.23.5.2847.jar | None      |
	| LCHIJA | forge     | 14.23.5.2847 | forge-1.12.2-14.23.5.2847.jar | None      |
	| LCHIJA | replaymod | 1.12.2-2.4.0 | replaymod-1.12.2-2.4.0.jar    | None      |

	Loaded coremods (and transformers): 
LoadingPlugin (replaymod-1.12.2-2.4.0.jar)

**Comment by artdeell** [comment]
It's a flaw inside the mod. It expects to save the temporary replay to /tmp
folder, which does not exist on Android. Ask the mod maintainers about
that.

пт, 9 окт. 2020 г., 15:37 KUALALUM <notifications@github.com>:
