### ISSUE TITLE
MCinaBox v0.1.4-p4在进入服务器时或者创建地图时产生MOD报错

### ISSUE THREAD

**Issue by xlxyvergil** [AOF-Dev/MCinaBox#723]
[crash-2020-12-04_11.11.10-client.txt](https://github.com/AOF-Dev/MCinaBox/files/5642370/crash-2020-12-04_11.11.10-client.txt)
**Describe the crash**

**To Reproduce**
Steps to reproduce the crash:
1. 安装MOD antiqueatlas-1.12.2-4.5.1.jar 
2. 点击创建世界或者进入包含该MOD的服务器
3. See the crash

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [小米mix2]
 - OS: [安卓9]
 - App Version [miui 12.0.1.0]

**Additional context**
Description: Unexpected error

java.lang.UnsatisfiedLinkError: /data/data/com.aof.mcinabox/files/runtime/boat/j2re-image/lib/aarch64/libfontmanager.so: dlopen failed: library "libfreetype.so.6" not found
    at java.lang.ClassLoader$NativeLibrary.load(Native Method)
    at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934)
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1838)
    at java.lang.Runtime.loadLibrary0(Runtime.java:871)
    at java.lang.System.loadLibrary(System.java:1124)
    at sun.font.FontManagerNativeLibrary$1.run(FontManagerNativeLibrary.java:61)
    at java.security.AccessController.doPrivileged(Native Method)
    at sun.font.FontManagerNativeLibrary.<clinit>(FontManagerNativeLibrary.java:32)
    at sun.font.SunFontManager$1.run(SunFontManager.java:339)
    at java.security.AccessController.doPrivileged(Native Method)
    at sun.font.SunFontManager.<clinit>(SunFontManager.java:335)
    at sun.font.FontDesignMetrics.getMetrics(FontDesignMetrics.java:264)
    at sun.swing.SwingUtilities2.getFontMetrics(SwingUtilities2.java:1125)
    at javax.swing.JComponent.getFontMetrics(JComponent.java:1626)
    at javax.swing.plaf.basic.BasicLabelUI.getPreferredSize(BasicLabelUI.java:245)
    at javax.swing.JComponent.getPreferredSize(JComponent.java:1662)
    at javax.swing.plaf.basic.BasicListUI.updateLayoutState(BasicListUI.java:1363)
    at javax.swing.plaf.basic.BasicListUI.maybeUpdateLayoutState(BasicListUI.java:1311)
    at javax.swing.plaf.basic.BasicListUI$Handler.valueChanged(BasicListUI.java:2623)
    at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:184)
    at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:164)
    at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:211)
    at javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:405)
    at javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:415)
    at javax.swing.DefaultListSelectionModel.setSelectionInterval(DefaultListSelectionModel.java:459)
    at javax.swing.JList.setSelectedIndex(JList.java:2216)
    at javax.swing.plaf.basic.BasicComboPopup.setListSelection(BasicComboPopup.java:1186)
    at javax.swing.plaf.basic.BasicComboPopup.access$300(BasicComboPopup.java:65)
    at javax.swing.plaf.basic.BasicComboPopup$Handler.itemStateChanged(BasicComboPopup.java:1015)
    at javax.swing.JComboBox.fireItemStateChanged(JComboBox.java:1223)
    at javax.swing.JComboBox.selectedItemChanged(JComboBox.java:1280)
    at javax.swing.JComboBox.contentsChanged(JComboBox.java:1330)
    at javax.swing.AbstractListModel.fireContentsChanged(AbstractListModel.java:118)
    at javax.swing.plaf.metal.MetalFileChooserUI$FilterComboBoxModel.propertyChange(MetalFileChooserUI.java:1073)
    at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
    at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
    at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
    at java.awt.Component.firePropertyChange(Component.java:8434)
    at javax.swing.JFileChooser.setFileFilter(JFileChooser.java:1473)
    at javax.swing.JFileChooser.addChoosableFileFilter(JFileChooser.java:1151)
    at javax.swing.JFileChooser.updateUI(JFileChooser.java:1839)
    at javax.swing.JFileChooser.setup(JFileChooser.java:371)
    at javax.swing.JFileChooser.<init>(JFileChooser.java:343)
    at javax.swing.JFileChooser.<init>(JFileChooser.java:296)
    at hunternif.mc.atlas.util.ExportImageUtil.<clinit>(ExportImageUtil.java:38)
    at hunternif.mc.atlas.client.gui.ExportProgressOverlay.draw(ExportProgressOverlay.java:29)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_721_ExportProgressOverlay_draw_Post.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.client.GuiIngameForge.post(GuiIngameForge.java:911)
    at net.minecraftforge.client.GuiIngameForge.renderGameOverlay(GuiIngameForge.java:207)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1098)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Affected level --
  Level name: MpServer
  All players: 1 total; [EntityPlayerSP['xlxyvergil'/502, l='MpServer', x=8.50, y=65.00, z=8.50]]
  Chunk stats: MultiplayerChunkCache: 0, 0
  Level seed: 0
  Level generator: ID 00 - default, ver 1. Features enabled: false

  Level generator options: 
  Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
  Level time: 0 game time, 0 day time
  Level dimension: 0
  Level storage version: 0x00000 - Unknown?
  Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
  Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
  Forced entities: 1 total; [EntityPlayerSP['xlxyvergil'/502, l='MpServer', x=8.50, y=65.00, z=8.50]]
  Retry entities: 0 total; []
  Server brand: fml,forge
  Server type: Integrated singleplayer server

[Uploading crash-2020-12-04_11.11.10-client.txt…]()

**Comment by TSaltedfishKing** [comment]
libfreetype.so.6缺失

**Comment by xlxyvergil** [comment]
官网上下载的64位运行库中也确实没有libfreetype.so.6，而电脑端的lib中没有该文件，是不是运行库中需要补充什么？

**Comment by longjunyu2** [comment]
Java运行库不完整

**Comment by xlxyvergil** [comment]
有解决方式么~这边重复安装运行库也无法解决.

**Comment by qaz6750** [comment]
我会尝试修复
(也许不会正功)

**Comment by qaz6750** [comment]
aarch32有libfreetype.so.6.可以尝试
