### ISSUE TITLE
MCinaBox crash when touch fingerprint scanner

### ISSUE THREAD

**Issue by Valdex** [AOF-Dev/MCinaBox#820]
Steps to reproduce the crash:
1. Go to MCinaBox
2. Click on Start the game
2.1. Touch Fingerprint scanner
3. See the crash

**Smartphone (please complete the following information):**
 - Device: Xiaomi Redmi Note 8 Pro 6/64
 - OS: Android 11 (legion os)
 - App Version: 0.1.4-p4

Log
```
01-11 12:22:28.691 E/AndroidRuntime(20464): Process: com.aof.mcinabox, PID: 20464
01-11 12:22:28.691 E/AndroidRuntime(20464): 	at com.aof.mcinabox.gamecontroller.controller.HardwareController.sendKey(HardwareController.java:65)
01-11 12:22:28.691 E/AndroidRuntime(20464): 	at com.aof.mcinabox.gamecontroller.input.otg.Keyboard.sendKeyEvent(Keyboard.java:65)
01-11 12:22:28.691 E/AndroidRuntime(20464): 	at com.aof.mcinabox.gamecontroller.input.otg.Keyboard.onKey(Keyboard.java:76)
01-11 12:22:28.691 E/AndroidRuntime(20464): 	at com.aof.mcinabox.gamecontroller.controller.HardwareController.dispatchKeyEvent(HardwareController.java:118)
01-11 12:22:28.695 W/ActivityTaskManager(1073):   Force finishing activity com.aof.mcinabox/.MainActivity
01-11 12:22:28.738 W/ActivityTaskManager(1073):   Force finishing activity com.aof.mcinabox/cosine.boat.BoatActivity
01-11 12:22:29.165 I/ActivityManager(1073): Process com.aof.mcinabox (pid 20464) has died: prcp TOP 
01-11 12:22:29.174 I/WindowManager(1073): WIN DEATH: Window{ebc1b44 u0 com.aof.mcinabox/cosine.boat.BoatActivity}
01-11 12:22:29.191 I/WindowManager(1073): WIN DEATH: Window{3d472f6 u0 com.aof.mcinabox/com.aof.mcinabox.MainActivity}
01-11 12:22:29.324 W/ActivityTaskManager(1073): Activity top resumed state loss timeout for ActivityRecord{e537869 u0 com.aof.mcinabox/cosine.boat.BoatActivity t-1 f}}
```

**Comment by Valdex** [comment]
same with 0.1.4-p5
