### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Warsini974** [AOF-Dev/MCinaBox#984]
[17:12:30] [Client thread/INFO]: Setting user: ieieiei
[17:12:30] [Client thread/INFO]: (Session ID is token:0:fb8699de-1a95-3119-90c1-4bed8571683d)
[17:12:36] [Client thread/INFO]: LWJGL Version: 2.9.3
[17:12:37] [Client thread/ERROR]: Couldn't set pixel format
org.lwjgl.LWJGLException: Could not create EGL context
	at org.lwjgl.opengl.BoatContextImplementation.nCreate(Native Method) ~[lwjgl.jar:?]
	at org.lwjgl.opengl.BoatContextImplementation.create(BoatContextImplementation.java:50) ~[lwjgl.jar:?]
	at org.lwjgl.opengl.ContextGL.<init>(ContextGL.java:134) ~[lwjgl.jar:?]
	at org.lwjgl.opengl.Display.create(Display.java:852) ~[lwjgl.jar:?]
	at org.lwjgl.opengl.Display.create(Display.java:759) ~[lwjgl.jar:?]
	at ave.ap(SourceFile:521) [1.8.8.jar:?]
	at ave.am(SourceFile:363) [1.8.8.jar:?]
	at ave.a(SourceFile:310) [1.8.8.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [1.8.8.jar:?]
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2/25/21 5:12 PM
Description: Initializing game

org.lwjgl.LWJGLException: Could not create EGL context
	at org.lwjgl.opengl.BoatContextImplementation.nCreate(Native Method)
	at org.lwjgl.opengl.BoatContextImplementation.create(BoatContextImplementation.java:50)
	at org.lwjgl.opengl.ContextGL.<init>(ContextGL.java:134)
	at org.lwjgl.opengl.Display.create(Display.java:852)
	at org.lwjgl.opengl.Display.create(Display.java:759)
	at org.lwjgl.opengl.Display.create(Display.java:741)
	at ave.ap(SourceFile:534)
	at ave.am(SourceFile:363)
	at ave.a(SourceFile:310)
	at net.minecraft.client.main.Main.main(SourceFile:124)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at org.lwjgl.opengl.BoatContextImplementation.nCreate(Native Method)
	at org.lwjgl.opengl.BoatContextImplementation.create(BoatContextImplementation.java:50)
	at org.lwjgl.opengl.ContextGL.<init>(ContextGL.java:134)
	at org.lwjgl.opengl.Display.create(Display.java:852)
	at org.lwjgl.opengl.Display.create(Display.java:759)
	at org.lwjgl.opengl.Display.create(Display.java:741)
	at ave.ap(SourceFile:534)
	at ave.am(SourceFile:363)

-- Initialization --
Details:
Stacktrace:
	at ave.a(SourceFile:310)
	at net.minecraft.client.main.Main.main(SourceFile:124)

**Comment by Warsini974** [comment]
Help pls
n

**Comment by Warsini974** [comment]
@TSaltedfishKing

**Comment by Warsini974** [comment]
@TSaltedfishKing
